/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/layouts/AppFooter.vue')['default']
    AppLayoutAuth: typeof import('./src/layouts/AppLayoutAuth.vue')['default']
    AppLayoutDashboard: typeof import('./src/layouts/AppLayoutDashboard.vue')['default']
    AppMenu: typeof import('./src/layouts/AppMenu.vue')['default']
    AppMenuItem: typeof import('./src/layouts/AppMenuItem.vue')['default']
    AppSidebar: typeof import('./src/layouts/AppSidebar.vue')['default']
    AppTopbar: typeof import('./src/layouts/AppTopbar.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    DashboardAppBreadcrumb: typeof import('./src/layouts/dashboard/AppBreadcrumb.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormField: typeof import('@primevue/forms/formfield')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('primevue/toast')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
