/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/layouts/AppFooter.vue')['default']
    AppLayoutAuth: typeof import('./src/layouts/AppLayoutAuth.vue')['default']
    AppLayoutDashboard: typeof import('./src/layouts/AppLayoutDashboard.vue')['default']
    AppMenu: typeof import('./src/layouts/AppMenu.vue')['default']
    AppMenuItem: typeof import('./src/layouts/AppMenuItem.vue')['default']
    AppSidebar: typeof import('./src/layouts/AppSidebar.vue')['default']
    AppTopbar: typeof import('./src/layouts/AppTopbar.vue')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DashboardAppBreadcrumb: typeof import('./src/layouts/dashboard/AppBreadcrumb.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    Tree: typeof import('primevue/tree')['default']
    ViewsDashboardBalance: typeof import('./src/components/views/dashboard/Balance.vue')['default']
    ViewsDashboardTransaction: typeof import('./src/components/views/dashboard/Transaction.vue')['default']
    ViewsDashboardWallet: typeof import('./src/components/views/dashboard/Wallet.vue')['default']
    ViewsMenuAdd: typeof import('./src/components/views/menu/Add.vue')['default']
    ViewsMenuEdit: typeof import('./src/components/views/menu/Edit.vue')['default']
    ViewsMenuList: typeof import('./src/components/views/menu/List.vue')['default']
    ViewsTransactionAdd: typeof import('./src/components/views/transaction/Add.vue')['default']
    ViewsTransactionDetail: typeof import('./src/components/views/transaction/Detail.vue')['default']
    ViewsTransactionList: typeof import('./src/components/views/transaction/List.vue')['default']
    ViewsWalletAdd: typeof import('./src/components/views/wallet/Add.vue')['default']
    ViewsWalletEdit: typeof import('./src/components/views/wallet/Edit.vue')['default']
    ViewsWalletTransaction: typeof import('./src/components/views/wallet/Transaction.vue')['default']
  }
  export interface ComponentCustomProperties {
    KeyFilter: typeof import('primevue/keyfilter')['default']
    StyleClass: typeof import('primevue/styleclass')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
